{% set name = "zbarlight" %}
{% set version = "2.3" %}
{% set sha256 = "9ddb37751121b8e575277b312510bd3d08839b4b465a42b873e8e25344b26698" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
  skip: True  # [win]   zbar not available on windows

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - zbar
  run:
    - python
    - setuptools
    - zbar
    - pillow

test:
  imports:
    - zbarlight

about:
  home: https://github.com/Polyconseil/zbarlight
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'lightweight, python 2 and 3 compatible Zbar bindings'

  description: |
    zbarlight is a simple wrapper for the zbar library. For now, it only allows
    to read QR codes but contributions, suggestions and pull requests are
    welcome.
  doc_url: https://github.com/Polyconseil/zbarlight
  dev_url: https://github.com/Polyconseil/zbarlight

extra:
  recipe-maintainers:
    - kdmurray91
