travis:
  secure:
    BINSTAR_TOKEN: sz+h45+XUd3oZ/6BCbDfG0glkvNqsVAX9L179wZ1yUX7jlwXAiONKOjcJpyL7nktBPCncALF9+19PqhWieJiiMTdLtGkfLsSyU4qDrq8lxcdgNQGd1ZXvjfJE1lyT94A5Tv8gAEjYMbB/dgSi6Q8BCcnLwQdN++qobZSe1eS0ooMaGELE7cO4LehB6xeLfE7vyboB8M9Tin85b3k2qB2ppmN2MY7tG3MLhiHIZWVJw9oua3Y0E0SfSIOdVlcXU3Hedr//ubmhoih1r7Of9x3JcFsuHTDtit95I0SF0BiOf46d0XpIQNoPD2qrWFDQssSk5X3lnFXkNsbM7b/c7pNmT77jyh8EZtVPJWZIijKosX/6qY1/aJno4+9GQv2KoBbcex5AtyLtXs06EvT+rRg+Q8n+wY1R070bxfVVRtzj8wb2BDQ0+HA2Zu5eA9eXFAAPV0UwdC8+Kt4fXyLzNYNi1XYwuiOqXxhAnxI2b7benagEWnalRG9VbuaSunMxezD499vt4heZCXjUxKqz80JaGy3BcsmwwqCwOUCSUq+nUo4Cxt3aOwdgvdBK3Cans8A0fVDsKcalcvPT0MAf0g+QDo9xCWeYTqwTXsb2wyTD1jvAQUSYi9yZCGupdj+XF+q7bv6o1DiOdeKXRgypCqJjKAMOExX38+EMAtGtG9la4c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
